name: Node.js Release CI

on:
  push:
    branches:
      - master

jobs:
  build:
    #  elevate permissions to allow commit and set up environment
    permissions: write-all
    runs-on: ubuntu-latest

    # Get environment containing vars and secrets defined in repo setting
    environment: production

    # Define steps
    steps:
    #  Checkout code
    - name: Checkout
      uses: actions/checkout@v3

    # Setup node js envrionment
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    #  Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the project if option available in package.json
    - name: Build if option present
      run: npm run build --if-present

    #  Make release using semantic release
    - name: Release using semantic release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release
