name: Node.js Test and Release CI

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all # Elevate permissions for the stage to tag and push commits )Not working for protected tags_

    runs-on: ubuntu-latest

    environment: production # Get environment containing vars and secrets

    strategy:
      matrix:
        node-version: [18.x]

    steps:

    #  Checkout code
    - name: Checkout
      uses: actions/checkout@v3

    # Setup node js envrionment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    #  Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the project if option available in package.json
    - name: Build if option present
      run: npm run build --if-present

    #  Make release using semantic release
    - name: Release using semantic release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release
